### ISSUE TITLE
Timestamp Issue

### ISSUE THREAD

**Issue by ddurvaux** [sysforensics/Landesk-Registry-Entry-Parser#1]
Hello,

This issues is probably not directly related to this project but maybe (also?) to the registry parser.

I'm currently extending your script to support the extraction of logon history information store behind the key \\Wow6432Node\LANDesk\Inventory\LogonHistory\Logons which have a set of Logon subkey.

Each logon generates 3 Logon entry:
1) User display name (like John Doe);
2) Username  (like DOMAIN\jdoe);
3) Groups ownership.

The timestamp of each of those entry is clearly the last logon time. I'm trying to add it to my display but the function subkeys() on registry "Logons" return an empty list.  I can loop on values() but then I cannot retrieve timestamp.  I dig into Registry module without being able to find a function or variable that could help.

Any idea on how I could retrieve a timestamp associated with a registry value?  RegRipper correctly display the timestamp so I'm sure it's there ;). In only need to figure out how to get access to it :-D.

I will send a merge request whenever change will be done.

Best regards,

David

**Comment by sysforensics** [comment]
Do you have a sample hive I can look at?  I only tested against a few set of hives and it's been awhile since I did that.

**Comment by ddurvaux** [comment]
I will try to produce a demo one tomorrow or at least send a sanitized regripper extract.

**Comment by ddurvaux** [comment]
Here a small extract from regripper

Wow6432Node\LANDesk\Inventory\LogonHistory\Logons
LastWrite: Tue Sep  8 07:49:27 2015
CN=JOHN DOE (FOOBAR),OU=Users,OU=FOO,OU=BAR,DC=COMPANY,DC=com  Logon: Fri Apr 17 19:58:43 2015
FOOBAR\jdoe  Logon: Fri Apr 17 19:58:43 2015
OU=Users,OU=FOO,OU=BAR,DC=COMPANY,DC=com<*> - OU=DEPARTMENT<*> OU=Users,OU=FOO,OU=BAR,DC=COMPANY,DC=com<*> Logon: Fri Apr 17 19:58:43 2015

Apparently it will be difficult to create a fake binary registry hive sanitized.

The following code permit to extract all the informations except timestamps:
```python
def getLogonInfo(reg_soft):
    entries = ["Wow6432Node\\Landesk\\Inventory\\LogonHistory\\Logons",
                "Landesk\\Inventory\\LogonHistory\\Logons"]

    user = None
    login = None
    attributes = None
    result = []
    count = 1

    for en in entries:
        try:
            logon_history = reg_soft.open(en)
            for logon in logon_history.values():
                if logon.value() == None:
                    continue

                # Rebuild information on users
                key_time = None
                if count == 1:
                    user = logon.value()
                    count = count +1
                elif count == 2:
                    login = logon.value()
                    count = count +1
                else:
                    attributes = logon.value()
                    result.append([key_time, user, login, attributes])
                    user = None
                    login = None
                    attributes = None
                    count = 1
        except Registry.RegistryKeyNotFoundException as e:
            continue
    return result

**Comment by sysforensics** [comment]
Try changing Landesk to LANDesk and see if that works.  Without samples
there isn't much I can do.

On Thursday, October 15, 2015, David Durvaux <notifications@github.com>
wrote:

> Here a small extract from regripper
>
> Wow6432Node\LANDesk\Inventory\LogonHistory\Logons
> LastWrite: Tue Sep 8 07:49:27 2015
> CN=JOHN DOE (FOOBAR),OU=Users,OU=FOO,OU=BAR,DC=COMPANY,DC=com Logon: Fri
> Apr 17 19:58:43 2015
> FOOBAR\jdoe Logon: Fri Apr 17 19:58:43 2015
> OU=Users,OU=FOO,OU=BAR,DC=COMPANY,DC=com<*> - OU=DEPARTMENT<*>
> OU=Users,OU=FOO,OU=BAR,DC=COMPANY,DC=com<*> Logon: Fri Apr 17 19:58:43 2015
>
> Apparently it will be difficult to create a fake binary registry hive
> sanitized.
>
> The following code permit to extract all the informations except
> timestamps:
>
> def getLogonInfo(reg_soft):
>     entries = ["Wow6432Node\\Landesk\\Inventory\\LogonHistory\\Logons",
>                 "Landesk\\Inventory\\LogonHistory\\Logons"]
>
>     user = None
>     login = None
>     attributes = None
>     result = []
>     count = 1
>
>     for en in entries:
>         try:
>             logon_history = reg_soft.open(en)
>             for logon in logon_history.values():
>                 if logon.value() == None:
>                     continue
>
>                 # Rebuild information on users
>                 key_time = None
>                 if count == 1:
>                     user = logon.value()
>                     count = count +1
>                 elif count == 2:
>                     login = logon.value()
>                     count = count +1
>                 else:
>                     attributes = logon.value()
>                     result.append([key_time, user, login, attributes])
>                     user = None
>                     login = None
>                     attributes = None
>                     count = 1
>         except Registry.RegistryKeyNotFoundException as e:
>             continue
>     return result
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sysforensics/Landesk-Registry-Entry-Parser/issues/1#issuecomment-148335679>
> .
>


-- 
Sent from Gmail Mobile

**Comment by ddurvaux** [comment]
It doesn't work but I think the issue is actually for this project.  I submitted a first code extension.  I will search for a way to get the info then submit another code proposal.
